export const type = Object.freeze({
  ENGLISH: "English",
  CHINESE: "Chinese",
});

export const key = Object.freeze({
  /**
   * Localization
   */
  LOCALIZATION_SELECTED_TEXT_KEY: "LOCALIZATION_SELECTED_TEXT_KEY",
  LOCALIZATION_SELECTED_TEXT_VALUE: "LOCALIZATION_SELECTED_TEXT_VALUE",
  LOCALIZATION_ENGLISH_ITEM_TEXT: "LOCALIZATION_ENGLISH_ITEM_TEXT",
  LOCALIZATION_CHINESE_ITEM_TEXT: "LOCALIZATION_CHINESE_ITEM_TEXT",

  /**
   * Sign in
   */
  SIGN_IN_TITLE: "SIGN_IN_TITLE",
  SIGN_IN_TITLE_DESC: "SIGN_IN_TITLE_DESC",
  SIGN_IN_INPUT_PLACEHOLDER: "SIGN_IN_INPUT_PLACEHOLDER",
  SIGN_IN_COMFIRM: "SIGN_IN_COMFIRM",
  /**
   * Room list
   */
  ROOM_LIST_CREATE_NEW_ROOM_TITLE: "ROOM_LIST_CREATE_NEW_ROOM_TITLE",
  ROOM_LIST_CREATE_NEW_ROOM_INPUT_PLACEHOLDER: "ROOM_LIST_CREATE_NEW_ROOM_INPUT_PLACEHOLDER",
  ROOM_LIST_CREATE_NEW_ROOM_COMFIRM: "ROOM_LIST_CREATE_NEW_ROOM_COMFIRM",
  ROOM_LIST_JOIN_ROOM: "ROOM_LIST_JOIN_ROOM",
  /**
   * Navigation
   */
  NAVIGATION_ROOM_LIST_TITLE: "NAVIGATION_ROOM_LIST_TITLE",
  NAVIGATION_CREATE_NEW_ROOM: "NAVIGATION_CREATE_NEW_ROOM",
  NAVIGATION_WELCOME: "NAVIGATION_WELCOME",
  NAVIGATION_SIGN_OUT: "NAVIGATION_SIGN_OUT",
  /**
   * Chat room
   */
  CHAT_ROOM_MEDIA_CONSTRAINT_CAMERA: "CHAT_ROOM_MEDIA_CONSTRAINT_CAMERA",
  CHAT_ROOM_MEDIA_CONSTRAINT_SCREEN: "CHAT_ROOM_MEDIA_CONSTRAINT_SCREEN",
  CHAT_ROOM_MESSAGE_TYPE_TEXT: "CHAT_ROOM_MESSAGE_TYPE_TEXT",
  CHAT_ROOM_MESSAGE_TYPE_FILE: "CHAT_ROOM_MESSAGE_TYPE_FILE",
  CHAT_ROOM_MESSAGE_TEXT_INPUT_PLACEHOLDER: "CHAT_ROOM_MESSAGE_TEXT_INPUT_PLACEHOLDER",
  CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_IDLE: "CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_IDLE",
  CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_FILE: "CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_FILE",
  CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_FILE_PLURAL:
    "CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_FILE_PLURAL",
  CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_ADDED: "CHAT_ROOM_MESSAGE_FILE_INPUT_PLACEHOLDER_ADDED",
  /**
   * Time description
   */
  YEARS_AGO: "YEARS_AGO",
  MONTHS_AGO: "MONTHS_AGO",
  DAYS_AGO: "DAYS_AGO",
  HOURS_AGO: "HOURS_AGO",
  MINUTES_AGO: "MINUTES_AGO",
  SECONDS_AGO: "SECONDS_AGO",
});